### ISSUE TITLE
Add CFP form

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage18#12]
Requires input from @evildmp.  What questions do we want to ask on the CFP?

**Comment by evildmp** [comment]
Fields:

* text field: Tell us a bit about yourself (required)
   `help_text`: Introduce yourself -  tell us about what you do, where you come from and so on.
* text field: Tell us how you feel attending PyCon UK will be of value (required)
   `help_text`: This can include its value to you, the conference itself, the wider Python community, your own society, or anything at all. 
* Choices (required): 
  * I'd like to request a free ticket, but don't need other financial assistance
  * I'd like to request a free ticket and additional financial assistance
* text field: What amount in financial assistance would make it possible for you to attend the conference without hardship? (required)
   `help_text`: Please ensure you specify the currency (preferably in Sterling)
* text field: Please break down the costs you anticipate for travel, accommodation and daily expenses (required)
   `help_text`: Please see our <a href="https://2018.pyconuk.org/travel-accommodation" target="_blank">travel and accommodation guidance pages</a> to help calculate your costs.
* multiple choices: On which days do you plan to attend the conference? (required)
