### ISSUE TITLE
Add financial assistance form

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage18#13]
Requires input from @evildmp.  What questions do we want to ask on the application form?

**Comment by evildmp** [comment]
Introductory text:

> Our financial assistance programme exists to support attendees who might otherwise find it difficult to attend the conference. We have a budget set aside for this purpose.
>
> We welcome applications from all attendees, and strongly encourage you to apply if it would make it easier for you to attend. Many of your fellow attendees will be doing the same, including many speakers and even members of the conference organisation team.
>
> Financial assistance includes free or discounted tickets, and funds to cover the costs of travel, accommodation and other expenses.
>
> We'd love to be able to help all those who submit applications, but our funds are not unlimited, so we can't meet all requests. We do our best to maximise the impact of our financial assistance funding.
>
> The financial assistance programme prioritises speakers. We also use it to support attendees from groups who are under-represented in our community and at our events, as part of our efforts to make [PyCon UK as inclusive and diverse as possible](https://2018.pyconuk.org/diversity-inclusion-accessibility/).
>
> Whoever you are, however, and whatever your needs, **please do apply if we might be able to help you attend**. Your application will be treated in complete confidence. 
>
> Thanks for applying. We hope we'll be able to help.

**Comment by kirknorthrop** [comment]
From #12 
Fields:

* text field: Tell us a bit about yourself (required)
   `help_text`: Introduce yourself -  tell us about what you do, where you come from and so on.
* text field: Tell us how you feel attending PyCon UK will be of value (required)
   `help_text`: This can include its value to you, the conference itself, the wider Python community, your own society, or anything at all. 
* Choices (required): 
  * I'd like to request a free ticket, but don't need other financial assistance
  * I'd like to request a free ticket and additional financial assistance
* text field: What amount in financial assistance would make it possible for you to attend the conference without hardship? (required)
   `help_text`: Please ensure you specify the currency (preferably in Sterling)
* text field: Please break down the costs you anticipate for travel, accommodation and daily expenses (required)
   `help_text`: Please see our <a href="https://2018.pyconuk.org/travel-accommodation" target="_blank">travel and accommodation guidance pages</a> to help calculate your costs.
* multiple choices: On which days do you plan to attend the conference? (required)
