### ISSUE TITLE
Set up DNS

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage18#22]
We need the following DNS changes made:

* staging.hq.pyconuk.org should point to the ironcage18-staging app on heroku
* 2018.hq.pyconuk.org should point to the ironcage18 app on heroku

Additionally, we need to set up Mailgun so that we can send from these domains.  @ghickman did this last year, and I hope he remembers what's required!

**Comment by ghickman** [comment]
* [ ] Get access to both apps
* [ ] Add ALIAS certs pointing to `<domain>.herokudns.org` as per [docs](https://devcenter.heroku.com/articles/ssl#migrate-from-ssl-endpoint-to-heroku-ssl)
* [ ] Set up custom domains on both apps
* [ ] Enable [ACM](https://devcenter.heroku.com/articles/automated-certificate-management) for both apps
