### ISSUE TITLE
Add Ts & Cs

### ISSUE THREAD

**Issue by inglesp** [PyconUK/ironcage18#33]
I believe @doismellburning is putting some Ts & Cs together.

Do we have an estimate for when it'll be done?

**Comment by doismellburning** [comment]
This is the first I’ve heard of it. I can put something together for the end of next week though.

**Comment by inglesp** [comment]
@doismellburning Oh -- I've been misinformed (quite possibly by myself, sorry).

There's been quite a bit of discussion on Slack about this over the weekend, and there's now a PR.  You certainly said the other day that you'd like to review the Ts & Cs -- please could you review #41?
